# Generated by Django 4.1.3 on 2023-06-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario", old_name="apellido_1", new_name="nombre_completo",
        ),
        migrations.RemoveField(model_name="usuario", name="apellido_2",),
        migrations.RemoveField(model_name="usuario", name="nombre_1",),
        migrations.RemoveField(model_name="usuario", name="nombre_2",),
        migrations.AddField(
            model_name="usuario",
            name="email",
            field=models.EmailField(default="none", max_length=254),
        ),
        migrations.AddField(
            model_name="usuario",
            name="password",
            field=models.CharField(default="none", max_length=20),
            preserve_default=False,
        ),
    ]
