# Generated by Django 4.1.3 on 2023-07-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_remove_usuario_extra_rrss_tarea_completado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="fecha_inicio",
            field=models.DateField(default=None),
        ),
    ]
