# Generated by Django 4.1.3 on 2023-07-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_noticia_fecha_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadisticas",
            name="valor",
            field=models.CharField(max_length=100),
        ),
    ]
